// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgnuptkcpqrpsdwstfom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnbnVwdGtjcHFycHNkd3N0Zm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDM5MjYsImV4cCI6MjA2OTE3OTkyNn0.gHPfgjM1WFqVZ1l4i3upXW3TquE7RuGcT8LwJ151Qik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});